# Generated by Django 5.0 on 2024-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIDSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='pcapng_file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='pcap_file',
            field=models.FileField(max_length=400, upload_to='uploads/'),
        ),
    ]
