# Generated by Django 5.0 on 2024-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NIDSApp', '0003_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('protocol_type', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=50)),
                ('src_bytes', models.IntegerField()),
                ('dst_bytes', models.IntegerField()),
                ('urgent', models.IntegerField()),
                ('num_failed_logins', models.IntegerField()),
                ('serror_rate', models.FloatField()),
                ('rerror_rate', models.FloatField()),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
